{"name": "Ошибка: передан несуществующий id курьера", "status": "passed", "start": 1761069051339, "stop": 1761069051578, "uuid": "22b880da-3faf-4483-acc5-eaa0ff2d93f3", "historyId": "faaa7d748d9f15a08926a42b85c9d893", "testCaseId": "faaa7d748d9f15a08926a42b85c9d893", "fullName": "tests.test_order_accept.TestAcceptOrder#test_accept_order_with_invalid_courier_id_fails", "labels": [{"name": "feature", "value": "Order API"}, {"name": "story", "value": "Принятие заказа (Назначение курьера)"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "5476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}], "titlePath": ["tests", "test_order_accept.py", "TestAcceptOrder"]}